# This is based on https://medium.com/zendesk-engineering/a-github-actions-workflow-to-generate-publish-your-hugo-website-f36375e56cf7
#                  https://gist.githubusercontent.com/superpeteblaze/927aa85e9ed09682a6f3dc01b26e3736/raw/a215b81c08f051e752d1aaa38dbedabfc913a899/hugo_gh-pages.yml

# Workflow to build and deploy site to Github Pages using Hugo

# Name of Workflow
name: Build a Pull Request

# Controls when the action will run. Triggers the workflow on push only for the main branch
on:
  pull_request_target:
    paths:
    - 'docs/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'
          extended: true

    - name: Clean public directory
      run: rm -rf public

    - name: Build
      run: cd docs && hugo --minify --theme book